version: '3.8'
services:
  my-kafka:
    image: confluentinc/cp-kafka:5.5.1
    container_name: my-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://my-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper:2181
    depends_on:
      - my-zookeeper
    networks:
      - my-network
  my-zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    container_name: my-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my-network
  my-postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
networks:
  my-network:
